# Project information
site_name: Coding Practice

# Configuration
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.path
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

# Plugins
plugins:
  - search
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - LC Solutions:
    - LC Solutions 1 to 99:
      - LC26 Remove duplicates from sorted array: lc-solutions/lc0001-0099/lc0026-remove-duplicates-from-sorted-array.md
      - LC27 Remove element: lc-solutions/lc0001-0099/lc0027-remove-element.md
      - LC75 Sort colors: lc-solutions/lc0001-0099/lc0075-sort-colors.md
      - LC80 Remove duplicates from sorted array II: lc-solutions/lc0001-0099/lc0080-remove-duplicates-from-sorted-array-ii.md
      - LC88 Merge sorted array: lc-solutions/lc0001-0099/lc0088-merge-sorted-array.md
    - LC Solutions 100 to 199:
      - LC189 Rotate array: lc-solutions/lc0100-0199/lc0189-rotate-array.md
    - LC Solutions 200 to 299:
      - LC209 Minimum size subarray sum: lc-solutions/lc0200-0299/lc0209-minimum-size-subarray-sum.md
    - LC Solutions 400 to 499:
      - LC448 Find all numbers disappeared in an array: lc-solutions/lc0400-0499/lc0448-find-all-numbers-disappeared-in-an-array.md
      - LC485 Max consecutive ones: lc-solutions/lc0400-0499/lc0485-max-consecutive-ones.md
      - LC487 Max consecutive ones II: lc-solutions/lc0400-0499/lc0487-max-consecutive-ones-ii.md
    - LC Solutions 500 to 599:
      - LC560 Subarray sum equals K: lc-solutions/lc0500-0599/lc0560-subarray-sum-equals-k.md
    - LC Solutions 700 to 799:
      - LC713 Subarray product less than k: lc-solutions/lc0700-0799/lc0713-subarray-product-less-than-k.md
    - LC Solutions 800 to 899:
      - LC862 Shortest subarray with sum at least k: lc-solutions/lc0800-0899/lc0862-shortest-subarray-with-sum-at-least-k.md
    - LC Solutions 900 to 999:
      - LC974 Subarray sums divisible by K: lc-solutions/lc0900-0999/lc0974-subarray-sums-divisible-by-k.md
    - LC Solutions 1000 to 1499:
      - LC1004 Max consecutive ones III: lc-solutions/lc1000-1099/lc1004-max-consecutive-ones-iii.md
  # - LC Solutions 1500 to 1999:
  - Tag: tags.md