# Project information
site_name: Coding Practice

# Configuration
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.path
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

# Plugins
plugins:
  - search
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Data Structure:
    - Queue: data-structure/queue/queue.md
    - Stack: data-structure/stack/stack.md
    - Linked List: data-structure/linked-list/linked-list.md
    - Disjoint Set: data-structure/disjoint-set/disjoint-set.md
  - Algorithms:
    - Binary Search: algorithms/binary-search.md
    - Dynamic Programming: algorithms/dynamic-programming.md
    - Graph:
      - algorithms/graph/index.md
      - Breadth-First Search: algorithms/graph/breadth-first-search.md
      - Depth-First Search: algorithms/graph/depth-first-search.md
      - Kruskal Algorithm: algorithms/graph/kruskal-algorithm.md
    - Recursion: algorithms/recursion.md
    - Sorted Array Tips: algorithms/sorting/sorted-array-tips.md
  - LC Solutions:
    - lc-solutions/index.md
    - LC 1 to 99:
      - 1 Two sum: lc-solutions/lc0001-0099/lc0001-two-sum.md
      - 2 Add two numbers: lc-solutions/lc0001-0099/lc0002-add-two-numbers.md
      - 4 Median of two sorted arrays: lc-solutions/lc0001-0099/lc0004-median-of-two-sorted-arrays.md
      - 15 3sum: lc-solutions/lc0001-0099/lc0015-3sum.md
      - 18 4sum: lc-solutions/lc0001-0099/lc0018-4sum.md
      - 20 Valid parentheses: lc-solutions/lc0001-0099/lc0020-valid-parentheses.md
      - 21 Merge two sorted list: lc-solutions/lc0001-0099/lc0021-merge-two-sorted-lists.md
      - 23 Merge k sorted list: lc-solutions/lc0001-0099/lc0023-merge-k-sorted-lists.md
      - 26 Remove duplicates from sorted array: lc-solutions/lc0001-0099/lc0026-remove-duplicates-from-sorted-array.md
      - 27 Remove element: lc-solutions/lc0001-0099/lc0027-remove-element.md
      - 33 Search in rotated sorted array: lc-solutions/lc0001-0099/lc0033-search-in-rotated-sorted-array.md
      - 34 Find first and last position of element in sorted array: lc-solutions/lc0001-0099/lc0034-find-first-and-last-position-of-element-in-sorted-array.md
      - 35 Search insert position: lc-solutions/lc0001-0099/lc0035-search-insert-position.md
      - 69 Sqrt(x): lc-solutions/lc0001-0099/lc0069-sqrt-x.md
      - 74 Search a 2D matrix: lc-solutions/lc0001-0099/lc0074-search-a-2d-matrix.md
      - 75 Sort colors: lc-solutions/lc0001-0099/lc0075-sort-colors.md
      - 80 Remove duplicates from sorted array ii: lc-solutions/lc0001-0099/lc0080-remove-duplicates-from-sorted-array-ii.md
      - 81 Search in rotated sorted array ii: lc-solutions/lc0001-0099/lc0081-search-in-rotated-sorted-array-ii.md
      - 88 Merge sorted array: lc-solutions/lc0001-0099/lc0088-merge-sorted-array.md
      - 92 Reverse linked list ii: lc-solutions/lc0001-0099/lc0092-reverse-linked-list-ii.md
      - 94 Binary tree inorder traversal: lc-solutions/lc0001-0099/lc0094-binary-tree-inorder-traversal.md
    - LC 100 to 199:
      - 116 Populating next right pointers in each node: lc-solutions/lc0100-0199/lc0116-populating-next-right-pointers-in-each-node.md
      - 119 Pascal's triangle ii: lc-solutions/lc0100-0199/lc0119-pascals-triangle-ii.md
      - 133 Clone graph: lc-solutions/lc0100-0199/lc0133-clone-graph.md
      - 141 Linked list cycle: lc-solutions/lc0100-0199/lc0141-linked-list-cycle.md
      - 142 Linked list cycle ii: lc-solutions/lc0100-0199/lc0142-linked-list-cycle-ii.md
      - 143 Reorder list: lc-solutions/lc0100-0199/lc0143-reorder-list.md
      - 150 Evaluate reverse polish notation: lc-solutions/lc0100-0199/lc0150-evaluate-reverse-polish-notation.md
      - 153 Find minimum in rotated sorted array: lc-solutions/lc0100-0199/lc0153-find-minimum-in-rotated-sorted-array.md
      - 154 Find minimum in rotated sorted array ii: lc-solutions/lc0100-0199/lc0154-find-minimum-in-rotated-sorted-array-ii.md
      - 155 Min stack: lc-solutions/lc0100-0199/lc0155-min-stack.md
      - 167 Two sum ii - input array is sorted: lc-solutions/lc0100-0199/lc0167-two-sum-ii-input-array-is-sorted.md
      - 189 Rotate array: lc-solutions/lc0100-0199/lc0189-rotate-array.md
    - LC 200 to 299:
      - 200 Number of islands: lc-solutions/lc0200-0299/lc0200-number-of-islands.md
      - 203 Remove linked list elements: lc-solutions/lc0200-0299/lc0203-remove-linked-list-elements.md
      - 206 Reverse linked list: lc-solutions/lc0200-0299/lc0206-reverse-linked-list.md
      - 209 Minimum size subarray sum: lc-solutions/lc0200-0299/lc0209-minimum-size-subarray-sum.md
      - 225 Implement stack using queues: lc-solutions/lc0200-0299/lc0225-implement-stack-using-queues.md
      - 232 Implement queue using stacks: lc-solutions/lc0200-0299/lc0232-implement-queue-using-stacks.md
      - 234 Palindrome linked list: lc-solutions/lc0200-0299/lc0234-palindrome-linked-list.md
      - 237 Delete node in a linked list: lc-solutions/lc0200-0299/lc0237-delete-node-in-a-linked-list.md
      - 240 Search a 2D matrix ii: lc-solutions/lc0200-0299/lc0240-search-a-2d-matrix-ii.md
      - 261 Graph valid tree: lc-solutions/lc0200-0299/lc261-graph-valid-tree.md
      - 274 H-index: lc-solutions/lc0200-0299/lc0274-h-index.md
      - 275 H-index ii: lc-solutions/lc0200-0299/lc0275-h-index-ii.md
      - 278 First bad version: lc-solutions/lc0200-0299/lc0278-first-bad-version.md
      - 279 Perfect square: lc-solutions/lc0200-0299/lc0279-perfect-squares.md
      - 286 Walls and gates: lc-solutions/lc0200-0299/lc0286-walls-and-gates.md
    - LC 300 to 399:
      - 300 Longest increasing subsequence: lc-solutions/lc0300-0399/lc0300-longest-increasing-subsequence.md
      - 325 Maximum size subarray sum equals k: lc-solutions/lc0300-0399/lc0325-maximum-size-subarray-sum-equals-k.md
      - 354 Russian doll envelopes: lc-solutions/lc0300-0399/lc0354-russian-doll-envelopes.md
      - 367 Valid perfect square: lc-solutions/lc0300-0399/lc0367-valid-perfect-square.md
      - 374 Guess number higher or lower: lc-solutions/lc0300-0399/lc0374-guess-number-higher-or-lower.md
      - 394 Decode string: lc-solutions/lc0300-0399/lc0394-decode-string.md
    - LC 400 to 499:
      - 410 Split array largest sum: lc-solutions/lc0400-0499/lc0410-split-array-largest-sum.md
      - 429 N-ary tree level order traversal: lc-solutions/lc0400-0499/lc0429-n-ary-tree-level-order-traversal.md
      - 436 Find right interval: lc-solutions/lc0400-0499/lc0436-find-right-interval.md
      - 441 Arranging coins: lc-solutions/lc0400-0499/lc0441-arranging-coins.md
      - 445 Add two numbers ii: lc-solutions/lc0400-0499/lc0445-add-two-numbers-ii.md
      - 448 Find all numbers disappeared in an array: lc-solutions/lc0400-0499/lc0448-find-all-numbers-disappeared-in-an-array.md
      - 485 Max consecutive ones: lc-solutions/lc0400-0499/lc0485-max-consecutive-ones.md
      - 487 Max consecutive ones ii: lc-solutions/lc0400-0499/lc0487-max-consecutive-ones-ii.md
      - 494 Target sum: lc-solutions/lc0400-0499/lc0494-target-sum.md
    - LC 500 to 599:
      - 528 Random pick with weight: lc-solutions/lc0500-0599/lc0528-random-pick-with-weight.md
      - 540 Single element in a sorted array: lc-solutions/lc0500-0599/lc0540-single-element-in-a-sorted-array.md
      - 542 01 matrix: lc-solutions/lc0500-0599/lc0542-01-matrix.md
      - 547 Number of provinces: lc-solutions/lc0500-0599/lc0547-number-of-provinces.md
      - 560 Subarray sum equals K: lc-solutions/lc0500-0599/lc0560-subarray-sum-equals-k.md
    - LC 600 to 699:
      - 611 Valid triangle number: lc-solutions/lc0600-0699/lc0611-valid-triangle-number.md
      - 658 Find k closest elements: lc-solutions/lc0600-0699/lc0658-find-k-closest-elements.md
    - LC 700 to 799:
      - 702 Search in a sorted array of unknown size: lc-solutions/lc0700-0799/lc0702-search-in-a-sorted-array-of-unknown-size.md
      - 704 Binary search: lc-solutions/lc0700-0799/lc0704-binary-search.md
      - 713 Subarray product less than k: lc-solutions/lc0700-0799/lc0713-subarray-product-less-than-k.md
      - 733 Flood fill: lc-solutions/lc0700-0799/lc0733-flood-fill.md
      - 739 Daily temperatures: lc-solutions/lc0700-0799/lc0739-daily-temperatures.md
      - 744 Find smallest letter greater than target: lc-solutions/lc0700-0799/lc0744-find-smallest-letter-greater-than-target.md
      - 752 Open the lock: lc-solutions/lc0700-0799/lc0752-open-the-lock.md
      - 797 All paths from source to target: lc-solutions/lc0700-0799/lc0797-all-paths-from-source-to-target.md
    - LC 800 to 899:
      - 802 Find eventual safe states: lc-solutions/lc0800-0899/lc0802-find-eventual-safe-states.md
      - 841 Keys and rooms: lc-solutions/lc0800-0899/lc0841-keys-and-rooms.md
      - 852 Peak index in a mountain array: lc-solutions/lc0800-0899/lc0852-peak-index-in-a-mountain-array.md
      - 862 Shortest subarray with sum at least k: lc-solutions/lc0800-0899/lc0862-shortest-subarray-with-sum-at-least-k.md
      - 875 Koko eating bananas: lc-solutions/lc0800-0899/lc0875-koko-eating-bananas.md
      - 876 Middle of the linked list: lc-solutions/lc0800-0899/lc0876-middle-of-the-linked-list.md
      - 896 Monotonic array: lc-solutions/lc0800-0899/lc0896-monotonic-array.md
    - LC 900 to 999:
      - 904 Fruit into baskets: lc-solutions/lc0900-0999/lc0904-fruit-into-baskets.md
      - 974 Subarray sums divisible by k: lc-solutions/lc0900-0999/lc0974-subarray-sums-divisible-by-k.md
      - 981 Time Based Key-Value Store: lc-solutions/lc0900-0999/lc0981-time-based-key-value-store.md
      - 994 Rotting oranges: lc-solutions/lc0900-0999/lc0994-rotting-oranges.md
    - LC 1000 to 1099:
      - 1004 Max consecutive ones iii: lc-solutions/lc1000-1099/lc1004-max-consecutive-ones-iii.md
      - 1011 Capacity to ship packages within D days: lc-solutions/lc1000-1099/lc1011-capacity-to-ship-packages-within-d-days.md
      - 1059 All paths from source lead to destination: lc-solutions/lc1000-1099/lc1059-all-paths-from-source-lead-to-destination.md
      - 1091 Shortest path in binary matrix: lc-solutions/lc1000-1099/lc1091-shortest-path-in-binary-matrix.md
      - 1099 Two sum less than k: lc-solutions/lc1000-1099/lc1099-two-sum-less-than-k.md
    - LC 1100 to 1199:
      - 1129 Shortest path with alternating colors: lc-solutions/lc1100-1199/lc1129-shortest-path-with-alternating-colors.md
      - 1146 Snapshot array: lc-solutions/lc1100-1199/lc1146-snapshot-array.md
    - LC 1200 to 1299:
      - 1231 Divide chocolate: lc-solutions/lc1200-1299/lc1231-divide-chocolate.md
      - 1232 Check if it is a straight line: lc-solutions/lc1200-1299/lc1232-check-if-it-is-a-straight-line.md
      - 1235 Maximum profit in job scheduling: lc-solutions/lc1200-1299/lc1235-maximum-profit-in-job-scheduling.md
      - 1283 Find the smallest divisor given a threshold: lc-solutions/lc1200-1299/lc1283-find-the-smallest-divisor-given-a-threshold.md
    - LC 1300 to 1399:
      - 1351 Count negative numbers in a sorted matrix: lc-solutions/lc1300-1399/lc1351-count-negative-numbers-in-a-sorted-matrix.md
    - LC 1400 to 1499:
      - 1498 Number of subsequences that satisfy the given sum condition: lc-solutions/lc1400-1499/lc1498-number-of-subsequences-that-satisfy-the-given-sum-condition.md
    - LC 1500 to 1599:
      - 1533 Find the index of the large integer: lc-solutions/lc1500-1599/lc1533-find-the-index-of-the-large-integer.md
      - 1539 Kth missing positive number: lc-solutions/lc1500-1599/lc1539-kth-missing-positive-number.md
    - LC 1600 to 1699:
      - 1631 Path with minimum effort: lc-solutions/lc1600-1699/lc1631-path-with-minimum-effort.md
    - LC 1700 to 1799:
      - 1721 Swapping nodes in a linked list: lc-solutions/lc1700-1799/lc1721-swapping-nodes-in-a-linked-list.md
    - LC 1800 to 1899:
      - 1802 Maximum value at a given index in a bounded array: lc-solutions/lc1800-1899/lc1802-maximum-value-at-a-given-index-in-a-bounded-array.md
      - 1870 Minimum speed to arrive on time: lc-solutions/lc1800-1899/lc1870-minimum-speed-to-arrive-on-time.md
    - LC 1900 to 1999:
      - 1971 Find if Path Exists in Graph: lc-solutions/lc1900-1999/lc1971-find-if-path-exists-in-graph.md
    - LC 2000 to 2099:
      - 2300 Successful pairs of spells and portions: lc-solutions/lc2000-2099/lc2300-successful-pairs-of-spells-and-portions.md
      - 2095 Delete the middle node of a linked list: lc-solutions/lc2000-2099/lc2095-delete-the-middle-node-of-a-linked-list.md
  # - LC 1500 to 1999:
  - Tag: tags.md