# Project information
site_name: Coding Practice

# Configuration
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

# Plugins
plugins:
  - search
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - LC Solutions:
    - LC Solutions 1 to 99:
      - LC26 Remove duplicates from sorted array: lc-solutions/lc0001-0099/lc0026-remove-duplicates-from-sorted-array.md
      - LC27 Remove element: lc-solutions/lc0001-0099/lc0027-remove-element.md
      - LC80 Remove duplicates from sorted array II: lc-solutions/lc0001-0099/lc0080-remove-duplicates-from-sorted-array-ii.md
  # - LC Solutions 500 to 999:
  # - LC Solutions 1000 to 1499:
  # - LC Solutions 1500 to 1999:
  - Tag: tags.md